trigger:
  - main

variables:
  NODE_ENV: prod
  NODE_PORT: 3001

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              dockerfile: '**/Dockerfile'
              tags: '1.0.0'
              arguments: |
                --build-arg NODE_ENV=$(NODE_ENV) --build-arg NODE_PORT=$(NODE_PORT)

          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            inputs:
              command: push
              containerRegistry: 'registryConnection'
              repository: 'test-api'
              tags: '1.0.0'
