trigger:
  - main

pool: local-agent

resources:
  - repo: self

variables:
  - group: "CICD"
  - name: app_var
    value: $[variables.appVariable]
  NODE_ENV: prod
  NODE_PORT: 3001

parameters:
  - name: tag
    default: "$(Build.BuildId)"
  - name: imageName
    default: "test-api"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build

        steps:
          - script: |
              echo "var=$(app_var)"
              echo "tag= ${{ parameters.tag }}"

          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              repository: ${{ parameters.imageName }}
              containerRegistry: 'registryConnection'
              dockerfile: "**/qa.dockerfile"
              tags: ${{ parameters.tag }}
              arguments: '--build-arg APP_ENV="$(app_var)"'

          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              containerRegistry: 'registryConnection'
              repository: ${{ parameters.imageName }}
              tags: |
                ${{ parameters.tag }}
